### ISSUE TITLE
starting a map with c+ 2.2.4 enabled crashes the game (update: crash possibly caused by settings corruption by previous plugin version)

### ISSUE THREAD

**Issue by OoDeeR** [NuggoDEV/CountersPlus#105]
I've had the crash upon ingame-reload on the previous version. C+ was simply not working after that anymore, but I could still play the game without it showing up (just base game UI).
Today I installed v2.2.4, went into the game, enabled C+ from its own settings UI, started a map and it simply went black with no further response from the game
[_latest.log](https://github.com/Caeden117/CountersPlus/files/7656202/_latest.log)
.

**Comment by OoDeeR** [comment]
very quick update: the issue seems to be related to a corrupted settings file (probably caused by the crash in the previous version). Deleting the old file and letting the plugin make a new one fixes the issue.
Suggestion: add validity check of the settings to avoid such scenarios.

**Comment by Creeper55k** [comment]
Hi! I am a contributor to the original version upgrade. I am looking into the issue and will see what's happening. The original version that was merged seem to not cause issues except only with Shaffuru which caused a calculation error with PB accuracy counter. The only thing to do in the meantime is to delete the original settings like you said. That seems to fix the issue. Is there any mod you were using that required Counters+ to work?

**Comment by Creeper55k** [comment]
> Hi! I am a contributor to the original version upgrade. I am looking into the issue and will see what's happening. The original version that was merged seem to not cause issues except only with Shaffuru which caused a calculation error with PB accuracy counter. The only thing to do in the meantime is to delete the original settings like you said. That seems to fix the issue. Is there any mod you were using that required Counters+ to work?

I mean like full combo percentage counter or PP counter or something similar

**Comment by Caeden117** [comment]
> Suggestion: add validity check of the settings to avoid such scenarios.

One step ahead of you, already done in commit a2d930a17d27c8655edc34663c1f0e7c0cf6f506 (although not published to any version just yet)

there looks like there are mod conflicts with Counters+; I am running a pretty barebones mod setup (core mods, Counters+, Chroma/NE and dependencies) and I am experiencing no issues whatsoever

**Comment by OoDeeR** [comment]
> I mean like full combo percentage counter or PP counter or something similar

I was using PPCounter, indeed, which currently seems incompatible with v2.2.4.
As the original problem seems resolved and was more likely caused by the v2.2.3 crash than anything else, this issue can be closed, imo.
Thanks for your work! <3
