### ISSUE TITLE
Not working in 1.27

### ISSUE THREAD

**Issue by ThunderAxolotl** [NuggoDEV/CountersPlus#128]
Mod seems to not be working in 1.27

**Comment by TaohRihze** [comment]
I got these errors in 1.27

[CRITICAL @ 21:39:08 | UnityEngine] MissingMethodException: System.Collections.Generic.IEnumerable`1<!!0> IReadonlyBeatmapData.GetBeatmapDataItems<!0>()
[CRITICAL @ 21:39:08 | UnityEngine] CountersPlus.Counters.NoteCountProcessors.NoteCountProcessor.get_Data () (at <6206b70ef8824806a1171d2381c2672d>:0)
[CRITICAL @ 21:39:08 | UnityEngine] CountersPlus.Counters.NoteCountProcessors.NoteCountProcessor.get_NoteCount () (at <6206b70ef8824806a1171d2381c2672d>:0)
[CRITICAL @ 21:39:08 | UnityEngine] CountersPlus.Counters.NotesLeftCounter.CounterInit () (at <6206b70ef8824806a1171d2381c2672d>:0)
[CRITICAL @ 21:39:08 | UnityEngine] CountersPlus.Counters.Event_Broadcasters.CounterEventBroadcaster.Initialize () (at <6206b70ef8824806a1171d2381c2672d>:0)
[CRITICAL @ 21:39:08 | UnityEngine] Zenject.InitializableManager.Initialize () (at <34fd6cc1ee2d4d3d8f9c65e77cc80832>:0)
[CRITICAL @ 21:39:08 | UnityEngine] Rethrow as ZenjectException: Error occurred while initializing IInitializable with type 'CounterEventBroadcaster'
[CRITICAL @ 21:39:08 | UnityEngine] Zenject.InitializableManager.Initialize () (at <34fd6cc1ee2d4d3d8f9c65e77cc80832>:0)
[CRITICAL @ 21:39:08 | UnityEngine] Zenject.MonoKernel.Initialize () (at <34fd6cc1ee2d4d3d8f9c65e77cc80832>:0)
[CRITICAL @ 21:39:08 | UnityEngine] Zenject.MonoKernel.Start () (at <34fd6cc1ee2d4d3d8f9c65e77cc80832>:0)

**Comment by truality-dev** [comment]
It seems like if you reset the config file, then it will start working, at least it did for me.

**Comment by TaohRihze** [comment]
Friend did following to get the mod working for me.
---
Downloaded the Counters+ repo from GitHub, opened it in Visual Studio, pointed the dependencies to the 1.27 version of them (Plugins-folder). If Heck is missing, download it from the Beatmods website, and toss it into the plugins folder, compile, and it should work

**Comment by ibillingsley** [comment]
I think only the "Notes Left" counter is broken.

Fix is here: https://github.com/rakkyo150/CounterPlus-Improved/commit/1c0a84e42598703898e1fe8ec0701dd2a4a7e1b1

**Comment by Trajor** [comment]
> I think only the "Notes Left" counter is broken.
> 
> Fix is here: [rakkyo150@1c0a84e](https://github.com/rakkyo150/CounterPlus-Improved/commit/1c0a84e42598703898e1fe8ec0701dd2a4a7e1b1)

Thanks, yes that worked for me, I was able to clone and Build this repo with this fix to add the 0 to GetBeatmapDataItems<NoteData>(0).  I verified it works in Beat Saber 1.27.0.

**Comment by DawnXofXFear** [comment]
It just stays on a black screen whenever i go in to configuration

**Comment by DeagleVR** [comment]
> It just stays on a black screen whenever i go in to configuration

FR my screen goes black

**Comment by Alyng0** [comment]
Still no worky even after the new release

**Comment by Caeden117** [comment]
would appreciate more than that

console log? description? anything?

**Comment by MagnusWestin** [comment]
works great now. Thank you for the update.

**Comment by Californ1a** [comment]
> It just stays on a black screen whenever i go in to configuration

> FR my screen goes black when i try to change my config

> Still no worky even after the new release

I had a similar issue for a while and finally looked at the log to try to figure it out. In my case, it was an incompatibility with [BeatLeaderModifiers](https://github.com/BeatLeader/beatleader-modifiers-mod/releases), a mod made for [a BL event](https://beatleader.xyz/event/23) that I just forgot to get rid of after the event ended. Once I removed that mod, then the Counters+ config menu was able to open normally again.
