### ISSUE TITLE
incompatibility with Beatsaberplus Game Tweaker

### ISSUE THREAD

**Issue by ICEDStriker** [NuggoDEV/CountersPlus#88]
When i disable the world particles in BS+ Game Tweaker these annoying random white particles are gone. After i installed Counters+ the particles were gone only in the menu and when i join a map they are back. When the map ends they are gone in the menu again.

**Comment by Caeden117** [comment]
Uhhhh, going to need a lot more information than this.

Counters+ does not touch anything related to particles, so currently I highly doubt that Counters+ is the problem.

**Comment by Striekfighter77** [comment]
i know m description was not very specific. i made a video maybe you understand now what i mean

https://youtu.be/2R2MVCAeBjk

**Comment by Caeden117** [comment]
Let me do a bit of digging into the BS+ code and see what exactly it does.

In the meantime, would you mind sending me your `latest.log` file in the `Beat Saber/Logs` folder?
